language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install pep8 --use-mirrors
  - pip install coverage --use-mirrors
script:
  - pep8 webvulnscan test
  - nosetests test --verbose --with-coverage --cover-package=webvulnscan --coverage-min-percentage=70
notifications:
  email:
    - phihag@phihag.de
    - liebig.richard@hotmail.com
